### ISSUE TITLE
Errors pasting in tables

### ISSUE THREAD

**Issue by orome** [aepsilon/turing-machine-viz#6]
I'm stumped with errors I keep stumbling over when I paste in a YAML table. For example 

```
table:
	b:
		' ': {write: '0', R: c}
	c:
		' ': {write: ' ', R: e}
	e:
		' ': {write: '1', R: f}
	f:
		' ': {write: ' ', R: b}

```
gives

> Possible duplicated mapping key

at the line for starting m-configuration 'c'.

What am I missing?

**Comment by aepsilon** [comment]
YAML doesn't support tabs (`\t`) for structural indentation.
https://yaml.org/faq.html
https://yaml.org/spec/1.2/spec.html#id2777534

The error points at the line after `c`. Without recognized indentation, https://nodeca.github.io/js-yaml/ seems to consider the lines with `' '` as duplicate keys in the same mapping. The error message could be improved; some other YAML parsers are able to report the tabs as invalid.

Instead, using spaces to indent works (the built-in editor is already configured for this):

```
table:
  b:
    ' ': {write: '0', R: c}
  c:
    ' ': {write: ' ', R: e}
  e:
    ' ': {write: '1', R: f}
  f:
    ' ': {write: ' ', R: b}
```

**Comment by orome** [comment]
(* smack *) Indeed! The consequences of too many years with IDEs that automatically replace tabs with spaces. I've begin to assume it happens everywhere!
